# Generated by Django 5.2 on 2025-07-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donate_day',
        ),
    ]
